parameters:
    twig_cache_directory: '%kernel.cache_dir%/twig'

services:
    _defaults:
        public: true
        autowire: true

    Symplify\Statie\Twig\:
        resource: '../src'

    Symplify\Statie\Twig\Renderable\TwigFileDecorator:
        arguments:
            $assetsRootDir: "@=container.hasParameter('assets_root_dir') ? parameter('assets_root_dir') : null"

    # twig setup
    Twig\Loader\ArrayLoader:
    Latte\Runtime\FilterExecutor:
    Granam\AssetsVersion\AssetsVersionInjector:
